 
 --WRITE A PROGRAM TO FIND SECOND HIGHEST SALARY FROM GIVEN TABLE.
WITH CTE AS(SELECT 
FIRST_NAME,
SALARY,
DENSE_RANK()
OVER(ORDER BY SALARY DESC) AS SECOND_HIGH_SAL FROM EMPLOYEES)SELECT FIRST_NAME,SALARY FROM CTE WHERE SECOND_HIGH_SAL=2;


 --WRITE A PROGRAM TO FIND SECOND HIGHEST SALARY FROM GIVEN TABLE.
WITH CTE AS(SELECT 
FIRST_NAME,
SALARY,
ROW_NUMBER()
OVER(ORDER BY SALARY DESC) AS SECOND_HIGH_SAL FROM EMPLOYEES)SELECT FIRST_NAME,SALARY FROM CTE WHERE SECOND_HIGH_SAL=2;


 --WRITE A PROGRAM TO FIND SECOND HIGHEST SALARY FROM GIVEN TABLE.
WITH SECOND_HIGH_SAL  AS(
SELECT FIRST_NAME,LAST_NAME,SALARY,ROW_NUMBER() 
OVER(ORDER BY SALARY DESC) AS SECOND_HIGHESTSALRY
FROM EMPLOYEES)
SELECT  FIRST_NAME,LAST_NAME,SALARY FROM SECOND_HIGH_SAL WHERE SECOND_HIGHESTSALRY=1; 
SELECT * FROM DEPARTMENT;

--WRITE A PROGRAM TO FIND DUPLICATE VALUE FROM GIVEN TABLE.
SELECT DEPTNAME,DEPTSALARY,COUNT(*) FROM DEPARTMENT GROUP BY DEPTNAME,DEPTSALARY HAVING  COUNT(*)>1 
